services:
  postgres:
    container_name: postgres-sql-bc
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  bc-api:
    container_name: bc-api
    image: bc/bc:1.1.0
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      - SPRING_JPA_DATABASE=${SPRING_JPA_DATABASE}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}

      - APPLICATION_FILE_UPLOAD_PHOTOS_OUTPUT_PATH=${APPLICATION_FILE_UPLOAD_PHOTOS_OUTPUT_PATH}

      - SERVER_PORT=${SERVER_PORT}

      - SPRING_THYMELEAF_PREFIX=classpath:/templates/
      - SPRING_THYMELEAF_SUFFIX=.html

      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      - SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE=${SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE}
      - SERVER_SERVLET_CONTEXT_PATH=${SERVER_SERVLET_CONTEXT_PATH}

      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_CONTAINER_NAME=${KEYCLOAK_CONTAINER_NAME}
      - KEYCLOAK_IMAGE=${KEYCLOAK_IMAGE}
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres

  bc-frontend:
    container_name: bc-frontend
    image: bc/bc-frontend:1.1.0
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      - SPRING_JPA_DATABASE=${SPRING_JPA_DATABASE}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}

      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}

      - APPLICATION_FILE_UPLOAD_PHOTOS_OUTPUT_PATH=${APPLICATION_FILE_UPLOAD_PHOTOS_OUTPUT_PATH}

      - SERVER_PORT=${SERVER_PORT}

      - SPRING_THYMELEAF_PREFIX=classpath:/templates/
      - SPRING_THYMELEAF_SUFFIX=.html

      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      - SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE=${SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE}
      - SERVER_SERVLET_CONTEXT_PATH=${SERVER_SERVLET_CONTEXT_PATH}

      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_CONTAINER_NAME=${KEYCLOAK_CONTAINER_NAME}
      - KEYCLOAK_IMAGE=${KEYCLOAK_IMAGE}
    ports:
      - 4200:80
    networks:
      - spring-demo
    depends_on:
      - bc-api

  keycloak:
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    image: ${KEYCLOAK_IMAGE}
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - spring-demo
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
