app = "bechangerapp"

[build]
  dockerfile = "Dockerfile"  # Dockerfile path

[[services]]
  internal_port = 8088  # Backend port
  public_port = 80      # Frontend port
  allow_tls = true

[[services]]
  internal_port = 8082  # Keycloak internal port
  public_port = 9090    # Expose keycloak on a different public port
  allow_tls = true
