services:
  postgres:
    container_name: postgres-sql-bc
    image: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: be_changer_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  bc-api:
    container_name: bc-api
    image: bc/bc:1.0.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-sql-bc:5432/be_changer_db
      - SPRING_DATASOURCE_USERNAME=yourusername
      - SPRING_DATASOURCE_PASSWORD=yourpassword
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
