/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  archived?: boolean;
  available?: boolean;
  brand?: string;
  coverImage?: string;
  description?: string;
  id?: number;
  identifier?: string;
  name?: string;
  owner?: string;
  rate?: number;
}
