/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedProductResponse {
  brand?: string;
  id?: number;
  identifier?: string;
  name?: string;
  rate?: number;
  returned?: boolean;
  returnedApproved?: boolean;
}
