spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
springdoc.default-produces-media-type=${SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}