spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.database=${SPRING_JPA_DATABASE}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.trust=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TRUST}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/be-changer-app
# application.cors.origins=http://localhost:4200,http://localhost:8080,http://localhost:8088

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://bechangerapp-ancient-frost-9304.fly.dev/realms/be-changer-app
application.cors.origins=https://bechangerapp-ancient-frost-9304.fly.dev:4200,http://bechangerapp-ancient-frost-9304.fly.dev:8080,http://bechangerapp-ancient-frost-9304.fly.dev:8088

spring.thymeleaf.prefix=${SPRING_THYMELEAF_PREFIX}
spring.thymeleaf.suffix=${SPRING_THYMELEAF_SUFFIX}

server.port=${SERVER_PORT}
server.address=0.0.0.0

application.file.upload.photos-output-path=${APPLICATION_FILE_UPLOAD_PHOTOS_OUTPUT_PATH}
