name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy Backend, frontend, Keycloak, and PostgreSQL
    steps:
      - name: Remove old backend container
        run: |
          sudo docker rm -f bc-api || true

      - name: Remove old frontend container
        run: |
          sudo docker rm -f bc-frontend || true

      - name: Remove old Keycloak container
        run: |
          sudo docker rm -f keycloak-bc || true

      - name: Remove old PostgreSQL container
        run: |
          sudo docker rm -f postgres-sql-bc || true

      - name: Remove old images
        run: |
          sudo docker image prune -a -f

      - name: Pull latest backend image
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bc-api:latest

      - name: Pull latest frontend image
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bc-frontend:latest

      - name: Pull latest Keycloak image
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-bc:latest

      - name: Pull latest PostgreSQL image
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/postgresql-sql-bc:latest

      - name: Run backend container
        run: |
          sudo docker run -d -p 8080:8088 --name bc-api ${{ secrets.DOCKERHUB_USERNAME }}/bc-api:latest

      - name: Run frontend container
        run: |
          sudo docker run -d -p 4200:80 --name bc-frontend ${{ secrets.DOCKERHUB_USERNAME }}/bc-frontend:latest

      - name: Run Keycloak container
        run: |
          sudo docker run -d -p 9090:8080 --name keycloak-bc ${{ secrets.DOCKERHUB_USERNAME }}/keycloak-bc:latest

      - name: Run PostgreSQL container
        run: |
          sudo docker run -d -p 5432:5432 --name postgres-sql-bc ${{ secrets.DOCKERHUB_USERNAME }}/postgres-sql-bc:latest
